#!/bin/bash

if [ $# -lt 3 ]; then
  echo "Usage: $0 PROJECT BUILDCONFIG_NAME PATH_TO_DOCKERFILE"
  exit 1
fi

PROJECT=$1
BC_NAME=$2
DOCKERFILE=$3

oc patch -n $PROJECT bc $BC_NAME --type json --patch '[{"op":"remove", "path":"/spec/strategy/dockerStrategy/from"}]' 1>/dev/null 2>/dev/null

set -e

PATCH=$(cat $DOCKERFILE | sed -e 's/"/\\"/g;s/$/\\n/g' | tr -d '\n')

oc patch -n $PROJECT bc $BC_NAME --patch '{"spec":{"source":{"dockerfile":"'"$PATCH"'"}}}'

