apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: simpleweb
  name: simpleweb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: simpleweb
    deploymentconfig: simpleweb
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 1
      maxUnavailable: 0
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
      labels:
        app: simpleweb
        deploymentconfig: simpleweb
    spec:
      containers:
      - livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: simpleweb
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - simpleweb
      from:
        kind: ImageStreamTag
        name: simpleweb:latest
    type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
  labels:
    build: simpleweb
  name: simpleweb
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: simpleweb:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleweb
  name: simpleweb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simpleweb
    deploymentconfig: simpleweb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: simpleweb
  name: simpleweb
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: simpleweb
    weight: 100
  wildcardPolicy: None